name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2
      - name: Compile Static Web Pages
        run: |
          go run main.go -d cmd/example/docs/src -o docs -p /go-service-doc -s bars.md
          mv docs/bars.html docs/index.html

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
